#+TITLE:     CS695 (Fall 2023): AI Safety and Assurance (or simply just AI Verification)
#+AUTHOR:    ThanhVu H. Nguyen

#+OPTIONS: num:nil 
#+OPTIONS: html-postamble:nil
#+OPTIONS: toc:nil num:nil ^:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://dynaroars.github.io/files/org.css"/>


#+BEGIN_SRC
    Instructor: ThanhVu (Vu) Nguyen
    Meetings: TBD

    Email: tvn@gmu.edu
    Office: 4430 Nguyen Engineering Building
    Office Hours: by appointment
#+END_SRC

* Description
This special topics course is a research seminar on **AI Verification and Analysis**.
The course will focus on active research areas in formal AI reasoning,
but the specific topics will be largely determined by a
combination of instructor fiat and the interests of the students.

* Prerequiste
- No prerequiste courses (but knowledge in linear algebra is strongly recommended)
- Programming knowledge (preferrably Python): capable of developing a project of roughly about 1000 LoCs

  
* Grading
You will be evaluated based on
1. weekly reading assignments and discussions,
2. a programming project

** Reading and Discussion ([[file:assignments.org][Schedule and Assignments]])

We will read papers covering various topics including the applications
of verification, testing, analysis, constraint solving, and abstraction
techniques to Deep Neural Networks such as Feedforward Neural Networks
(FNNs), Residual Networks (ResNet), Convolutional Neural Networks
(CNNs), and Recurrent Neural Networks (RNNs).

On average, we will discuss **two  papers** a week (~50 minutes to each paper). 
You are responsible for reading the sasigned papers in advance for any given discussion.

Each student will be assigned to **lead a paper** that talks about a technique
-  You will present **in depth** the paper you read
   - You will need to do a Powerpoint presentation style
   - This include providing concrete examples illustrating how the technique 
-   You will guide the discussion
-   **Tools**: Usually each research paper has a free implementation
    tool. I will take into account when evaluating if you try out the
    tool and discuss some interesting things that it can or cannot do
    (e.g., try the the tool on some small but nontrivial examples). This
    will help you understand the readings better and give you ideas on
    how to use existing tools in your own work.

At the beginning of **each paper** discussion I will choose at random up to
**three students** who is *not* the paper.
-   Each student will give a **five-minute** presentation that at least
    1. the problem (what is it? why is it interesting?)
    1. existing approaches (what are they? what are their limitations?)
    1. the proposed technical approach (also talk about the strengths of approach and how the approach addresses the weaknesses of  existing works)
    1. limitations of the proposed approach and lists ways in which it might be improved.
  
- The goals of this approach are to encourage all participants to read the material thoroughly in advance, to provide jumping-off points for detailed discussions, and to allow me to evaluate participation.


** Project

Each student will understand in depth (or own) a DNN analysis technique.  This technique is from one of the papers you lead.  Your project consists of 2 parts

*** Example Illustration
-   You will write a "blog" describing full concrete example illustrating the DNN technique assigned to you. This example will be due **2 weeks** after the paper is read.

- Format
  - Written in *Markdown*
  - Posted on the class's wiki
  - Consist of a full illustration on how the technique works on a given example (e.g., how Reluplex works on a simple DNN).


***  Programming Project ([[file:project.org][Project Info]])
- You will implement the DNN analysis technique using Python.
  - You will be given some example code in Python.
  - If you prefer a different language, talk to me first.
- In your "blog" entry above, you will write  how you apply your implementation to the example illustration you had.



* Honor Code

   As with all GMU courses, this class governed by the [[http://oai.gmu.edu/the-mason-honor-code/][GMU Honor Code]]. In this course, all assignments carry with them an implicit statement that it is the sole work of the author.

* Learning Disabilities

   Students with learning disabilities (or other conditions documented with GMU Office of Disability Services) who need academic accommodations should see me and contact the [[http://ods.gmu.edu/][Disability Resource Center]] (DRC) at (703)993-2474. I am more than happy to assist you, but all academic accommodations must be arranged through the DRC.


* Links
- [[file:assignments.org][Schedule and Assignments]]
- [[file:project.org][Project Info]]

   
